Repository prisma/prisma-engines, pull requests merged in 2023-06, with the labels that each got.

#3965 Stopgap: Postgres Expression Indexes
  schema-engine/connectors/schema-connector/src/warnings.rs
  schema-engine/connectors/sql-schema-connector/src/introspection/introspection_pair/model.rs
  schema-engine/connectors/sql-schema-connector/src/introspection/rendering/models.rs
  schema-engine/connectors/sql-schema-connector/src/introspection/warnings/model.rs
  schema-engine/sql-introspection-tests/tests/postgres/gin.rs
  schema-engine/sql-introspection-tests/tests/postgres/mod.rs
  schema-engine/sql-introspection-tests/tests/simple/cockroach/index_with_expression_column.sql
  schema-engine/sql-introspection-tests/tests/simple/postgres/index_with_expression_column.sql
  schema-engine/sql-schema-describer/src/postgres.rs
  schema-engine/sql-schema-describer/src/postgres/indexes_query.sql
  schema-engine/sql-schema-describer/tests/describers/postgres_describer_tests.rs
  schema-engine/sql-schema-describer/tests/describers/postgres_describer_tests/cockroach_describer_tests.rs
Labels: topic: stopgap

#4047 qe: Make jsonProtocol default and remove preview feature
  psl/psl-core/src/common/preview_features.rs
  psl/psl/tests/config/generators.rs
  query-engine/query-engine-node-api/src/engine.rs
  query-engine/query-engine/src/cli.rs
  query-engine/query-engine/src/context.rs
  query-engine/query-engine/src/opt.rs
Labels: topic: prisma5

#3990 For Prisma 5: refactor(introspection): remove version checker
  query-engine/schema/test-schemas/noalyss_folder.prisma
  query-engine/schema/test-schemas/odoo.prisma
  query-engine/schema/test-schemas/standupbot.prisma
  schema-engine/cli/tests/cli_tests.rs
  schema-engine/connectors/mongodb-schema-connector/src/sampler.rs
  schema-engine/connectors/schema-connector/src/introspection_result.rs
  schema-engine/connectors/schema-connector/src/lib.rs
  schema-engine/connectors/schema-connector/src/warnings.rs
  schema-engine/connectors/sql-schema-connector/src/introspection.rs
  schema-engine/connectors/sql-schema-connector/src/introspection/datamodel_calculator.rs
  schema-engine/connectors/sql-schema-connector/src/introspection/datamodel_calculator/context.rs
  schema-engine/connectors/sql-schema-connector/src/introspection/introspection_helpers.rs
  schema-engine/connectors/sql-schema-connector/src/introspection/introspection_map.rs
  schema-engine/connectors/sql-schema-connector/src/introspection/introspection_map/relation_names.rs
  schema-engine/connectors/sql-schema-connector/src/introspection/introspection_pair/default.rs
  schema-engine/connectors/sql-schema-connector/src/introspection/rendering/defaults.rs
  schema-engine/connectors/sql-schema-connector/src/introspection/version_checker.rs
  schema-engine/connectors/sql-schema-connector/src/introspection/warnings/model.rs
  schema-engine/core/src/state.rs
  schema-engine/json-rpc-api-build/methods/introspect.toml
  schema-engine/sql-introspection-tests/src/test_api.rs
  schema-engine/sql-introspection-tests/tests/add_prisma1_defaults/mod.rs
  schema-engine/sql-introspection-tests/tests/identify_version/mod.rs
  schema-engine/sql-introspection-tests/tests/introspection_tests.rs
  schema-engine/sql-migration-tests/tests/migrations/cockroachdb.rs
Labels: topic: prisma5

#3997 psl: support arrays in generator config
  psl/psl-core/src/configuration/generator.rs
  psl/psl-core/src/lib.rs
  psl/psl-core/src/validate/generator_loader.rs
  psl/psl/src/lib.rs
  psl/psl/tests/reformatter/generator_config.prisma
  psl/psl/tests/reformatter/generator_config.reformatted.prisma
  schema-engine/datamodel-renderer/src/configuration/generator.rs
  schema-engine/datamodel-renderer/src/value.rs
Labels: topic: prisma5

#4010 remove `experimentalFeatures` support
  psl/psl-core/src/validate/generator_loader.rs
Labels: topic: breaking, topic: prisma5

#3855 Rename migration-engine binary to schema-engine
  .buildkite/engineer
  .github/workflows/build-apple-intel.yml
  .github/workflows/build-apple-silicon.yml
  Makefile
  README.md
  libs/user-facing-errors/src/schema_engine.rs
  nix/all-engines.nix
  nix/cli-shell.nix
  schema-engine/ARCHITECTURE.md
  schema-engine/README.md
  schema-engine/cli/Cargo.toml
  schema-engine/cli/README.md
  schema-engine/cli/src/main.rs
  schema-engine/cli/tests/cli_tests.rs
  schema-engine/connectors/schema-connector/src/checksum.rs
  schema-engine/connectors/schema-connector/src/lib.rs
  schema-engine/connectors/schema-connector/src/migration.rs
  schema-engine/connectors/schema-connector/src/schema_connector.rs
  schema-engine/connectors/sql-schema-connector/src/flavour.rs
  schema-engine/core/src/api.rs
  schema-engine/core/src/commands.rs
  schema-engine/core/src/commands/diagnose_migration_history.rs
  schema-engine/core/src/core_error.rs
  schema-engine/core/src/rpc.rs
  schema-engine/core/src/state.rs
  schema-engine/datamodel-renderer/src/configuration/datasource.rs
  schema-engine/json-rpc-api-build/README.md
  schema-engine/json-rpc-api-build/methods/debugPanic.toml
  schema-engine/json-rpc-api-build/methods/diff.toml
  schema-engine/json-rpc-api-build/methods/ensureConnectionValidity.toml
  schema-engine/sql-migration-tests/bench.sh
  schema-engine/sql-migration-tests/src/multi_engine_test_api.rs
  schema-engine/sql-migration-tests/tests/single_migration_tests.rs
Labels: topic: breaking, topic: prisma5
