Repository prisma/prisma-engines, pull requests merged in 2023-12, with the labels that each got.

#4522 query-engine-wasm: fix build.sh with BSD sed
  query-engine/query-engine-wasm/build.sh
Labels: bug/2-confirmed, kind/bug, topic: driverAdapter - edge functions

#4552 feat(query-engine-wasm): shrink gzipped Wasm size down to 1.3MB
  psl/psl-core/src/lib.rs
  psl/psl-core/src/validate.rs
  psl/psl-core/src/validate/validation_pipeline.rs
  psl/psl/src/lib.rs
  query-engine/query-engine-wasm/Cargo.toml
  query-engine/query-engine-wasm/src/wasm/engine.rs
  query-engine/query-engine-wasm/wasm-opt.md
  query-engine/request-handlers/Cargo.toml
  query-engine/request-handlers/src/error.rs
Labels: topic: edge functions, topic: preview 👁

#4554 feat(driver-adapters): remove fallback for "provider"/"flavour"
  query-engine/driver-adapters/src/lib.rs
  query-engine/driver-adapters/src/proxy.rs
Labels: topic: edge functions, topic: preview 👁

#4562 feat(query-engine-wasm): fix example
  query-engine/query-engine-wasm/example/example.js
  query-engine/query-engine-wasm/example/package.json
  query-engine/query-engine-wasm/example/pnpm-lock.yaml
Labels: topic: edge functions, topic: preview 👁

#4576 Update Planetscale driver dep
  query-engine/driver-adapters/connector-test-kit-executor/package.json
  query-engine/driver-adapters/connector-test-kit-executor/pnpm-lock.yaml
Labels: topic: driver adapters

#4324 test: add Postgres v16 to GitHub Actions tests
  .github/workflows/test-query-engine-black-box.yml
  .github/workflows/test-query-engine.yml
  .github/workflows/test-schema-engine.yml
  .test_database_urls/postgres_16
  Makefile
  docker-compose.yml
  libs/test-setup/src/postgres.rs
  libs/test-setup/src/tags.rs
  query-engine/connector-test-kit-rs/query-tests-setup/src/connector_tag/mod.rs
  query-engine/connector-test-kit-rs/query-tests-setup/src/connector_tag/postgres.rs
  schema-engine/sql-introspection-tests/tests/commenting_out/postgres.rs
  schema-engine/sql-introspection-tests/tests/tables/mod.rs
  schema-engine/sql-introspection-tests/tests/views/postgresql.rs
  schema-engine/sql-migration-tests/src/multi_engine_test_api.rs
  schema-engine/sql-migration-tests/src/test_api.rs
  schema-engine/sql-migration-tests/tests/create_migration/create_migration_tests.rs
  schema-engine/sql-migration-tests/tests/migrations/postgres/introspection.rs
Labels: tech/engines, topic: tech debt

#4521 feat(query-engine-common): reduce duplicated code between `query-engine-node-api` and `query-engine-wasm`
  Cargo.lock
  libs/query-engine-common/Cargo.toml
  libs/query-engine-common/src/engine.rs
  libs/query-engine-common/src/error.rs
  libs/query-engine-common/src/lib.rs
  libs/query-engine-common/src/logger.rs
  libs/query-engine-common/src/tracer.rs
  query-engine/query-engine-node-api/Cargo.toml
  query-engine/query-engine-node-api/src/engine.rs
  query-engine/query-engine-node-api/src/error.rs
  query-engine/query-engine-node-api/src/functions.rs
  query-engine/query-engine-node-api/src/lib.rs
  query-engine/query-engine-node-api/src/logger.rs
  query-engine/query-engine-node-api/src/tracer.rs
  query-engine/query-engine-wasm/Cargo.toml
  query-engine/query-engine-wasm/src/wasm.rs
  query-engine/query-engine-wasm/src/wasm/engine.rs
  query-engine/query-engine-wasm/src/wasm/error.rs
  query-engine/query-engine-wasm/src/wasm/logger.rs
  query-engine/query-engine-wasm/src/wasm/tracer.rs
Labels: topic: preview 👁

#4569 feat(query-engine-wasm): `twiggy`-related utilities
  query-engine/query-engine-wasm/Cargo.toml
  query-engine/query-engine-wasm/README.md
  query-engine/query-engine-wasm/build.sh
  query-engine/query-engine-wasm/wasm-inspect.sh
Labels: topic: edge functions, topic: preview 👁
