Repository prisma/prisma-engines, pull requests merged in 2023-09, with the labels that each got.

#4220 fix(driver-adapters): Add studio command to smoke-tests
  query-engine/driver-adapters/js/smoke-test-js/README.md
  query-engine/driver-adapters/js/smoke-test-js/package.json
Labels: topic: driverAdapters

#4252 feat(driver-adapters): renamed npm scope to `@prisma/`
  query-engine/driver-adapters/js/adapter-neon/package.json
  query-engine/driver-adapters/js/adapter-neon/src/conversion.ts
  query-engine/driver-adapters/js/adapter-neon/src/neon.ts
  query-engine/driver-adapters/js/adapter-pg/package.json
  query-engine/driver-adapters/js/adapter-pg/src/conversion.ts
  query-engine/driver-adapters/js/adapter-pg/src/pg.ts
  query-engine/driver-adapters/js/adapter-planetscale/package.json
  query-engine/driver-adapters/js/adapter-planetscale/src/conversion.ts
  query-engine/driver-adapters/js/adapter-planetscale/src/planetscale.ts
  query-engine/driver-adapters/js/driver-adapter-utils/package.json
  query-engine/driver-adapters/js/pnpm-lock.yaml
  query-engine/driver-adapters/js/smoke-test-js/README.md
  query-engine/driver-adapters/js/smoke-test-js/package.json
  query-engine/driver-adapters/js/smoke-test-js/src/client/client.ts
  query-engine/driver-adapters/js/smoke-test-js/src/client/neon.http.test.ts
  query-engine/driver-adapters/js/smoke-test-js/src/client/neon.ws.test.ts
  query-engine/driver-adapters/js/smoke-test-js/src/client/pg.test.ts
  query-engine/driver-adapters/js/smoke-test-js/src/client/planetscale.test.ts
  query-engine/driver-adapters/js/smoke-test-js/src/engines/types/Library.ts
  query-engine/driver-adapters/js/smoke-test-js/src/libquery/libquery.ts
  query-engine/driver-adapters/js/smoke-test-js/src/libquery/neon.http.test.ts
  query-engine/driver-adapters/js/smoke-test-js/src/libquery/neon.ws.test.ts
  query-engine/driver-adapters/js/smoke-test-js/src/libquery/pg.test.ts
  query-engine/driver-adapters/js/smoke-test-js/src/libquery/planetscale.test.ts
  query-engine/driver-adapters/js/smoke-test-js/src/libquery/util.ts
Labels: topic: driverAdapters

#4257 test(qe) driver adapters tests GitHub action
  .github/workflows/query-engine-driver-adapters.yml
  query-engine/connector-test-kit-rs/query-tests-setup/src/connector_tag/js/node_process.rs
  query-engine/driver-adapters/js/connector-test-kit-executor/script/start_node.sh
  query-engine/driver-adapters/js/connector-test-kit-executor/src/index.ts
Labels: topic: driverAdapters

#4265 test(qe): driver adapters: parameterize test kit to test any driver adapter that we support
  .envrc
  .github/workflows/query-engine-driver-adapters.yml
  query-engine/connector-test-kit-rs/README.md
  query-engine/connector-test-kit-rs/query-tests-setup/src/connector_tag/js.rs
  query-engine/connector-test-kit-rs/query-tests-setup/src/connector_tag/js/external_process.rs
  query-engine/connector-test-kit-rs/query-tests-setup/src/lib.rs
  query-engine/driver-adapters/js/connector-test-kit-executor/package.json
  query-engine/driver-adapters/js/connector-test-kit-executor/src/index.ts
  query-engine/driver-adapters/js/connector-test-kit-executor/src/qe.ts
  query-engine/driver-adapters/js/pnpm-lock.yaml
  query-engine/driver-adapters/js/smoke-test-js/src/client/neon.http.test.ts
  query-engine/driver-adapters/js/smoke-test-js/src/client/neon.ws.test.ts
  query-engine/driver-adapters/js/smoke-test-js/src/client/pg.test.ts
  query-engine/driver-adapters/js/smoke-test-js/src/client/planetscale.test.ts
  query-engine/driver-adapters/js/smoke-test-js/src/libquery/neon.http.test.ts
  query-engine/driver-adapters/js/smoke-test-js/src/libquery/neon.ws.test.ts
  query-engine/driver-adapters/js/smoke-test-js/src/libquery/pg.test.ts
  query-engine/driver-adapters/js/smoke-test-js/src/libquery/planetscale.test.ts
  query-engine/query-engine-node-api/src/engine.rs
Labels: topic: driverAdapters

#4267 driver-adapters: Ensure error propogation works for `startTransaction`
  query-engine/driver-adapters/js/driver-adapter-utils/src/binder.ts
  query-engine/driver-adapters/js/smoke-test-js/package.json
  query-engine/driver-adapters/js/smoke-test-js/prisma/postgres/schema.prisma
  query-engine/driver-adapters/js/smoke-test-js/src/libquery/errors.test.ts
  query-engine/driver-adapters/js/smoke-test-js/src/libquery/libquery.ts
  query-engine/driver-adapters/js/smoke-test-js/src/libquery/util.ts
Labels: topic: driverAdapters

#4274 driver-adapters: Better result type
  query-engine/driver-adapters/js/adapter-neon/src/neon.ts
  query-engine/driver-adapters/js/adapter-pg/src/pg.ts
  query-engine/driver-adapters/js/adapter-planetscale/src/planetscale.ts
  query-engine/driver-adapters/js/driver-adapter-utils/src/binder.ts
  query-engine/driver-adapters/js/driver-adapter-utils/src/index.ts
  query-engine/driver-adapters/js/driver-adapter-utils/src/result.ts
  query-engine/driver-adapters/js/driver-adapter-utils/src/types.ts
Labels: topic: driverAdapters

#4268 test(qe) Improve DX for testing driver adapters locally in the query-engine and test prisma engines against postgres 13 using neon driver adapter
  .github/workflows/query-engine-driver-adapters.yml
  Makefile
  docker-compose.yml
  query-engine/connector-test-kit-rs/README.md
  query-engine/connector-test-kit-rs/query-tests-setup/src/config.rs
  query-engine/connector-test-kit-rs/query-tests-setup/src/connector_tag/js/external_process.rs
  query-engine/connector-test-kit-rs/query-tests-setup/src/connector_tag/mod.rs
  query-engine/connector-test-kit-rs/query-tests-setup/src/lib.rs
  query-engine/connector-test-kit-rs/query-tests-setup/src/runner/mod.rs
  query-engine/connector-test-kit-rs/test-configs/neon-ws-postgres13
  query-engine/connector-test-kit-rs/test-configs/pg-postgres13
  query-engine/connector-test-kit-rs/test-configs/postgres13
  query-engine/driver-adapters/js/connector-test-kit-executor/src/index.ts
  query-engine/driver-adapters/js/connector-test-kit-executor/src/qe.ts
  query-engine/query-engine-node-api/src/engine.rs
Labels: topic: driverAdapters

#4213 driver-adapters: Map neon errors to Prisma errors
  quaint/src/connector/postgres.rs
  quaint/src/connector/postgres/error.rs
  quaint/src/error.rs
  query-engine/driver-adapters/js/adapter-neon/src/neon.ts
  query-engine/driver-adapters/js/driver-adapter-utils/src/types.ts
  query-engine/driver-adapters/js/smoke-test-js/prisma/mysql/schema.prisma
  query-engine/driver-adapters/js/smoke-test-js/prisma/postgres/schema.prisma
  query-engine/driver-adapters/js/smoke-test-js/src/libquery/libquery.ts
  query-engine/driver-adapters/src/result.rs
Labels: topic: driverAdapters

#4266 ci(driver adapters): Workflow that runs driver adapters smoke test in CI
  .github/workflows/driver-adapter-smoke-tests.yml
  query-engine/driver-adapters/js/pnpm-lock.yaml
  query-engine/driver-adapters/js/smoke-test-js/package.json
  query-engine/driver-adapters/js/smoke-test-js/src/client/client.ts
  query-engine/driver-adapters/js/smoke-test-js/src/client/neon.http.test.ts
  query-engine/driver-adapters/js/smoke-test-js/src/libquery/util.ts
Labels: topic: driverAdapters

#4275 query-tests-setup: handle external process rpc thread panic
  query-engine/connector-test-kit-rs/query-tests-setup/src/connector_tag/js/external_process.rs
Labels: topic: driverAdapters

#4278 ci: Add libsql to smoke tests CI job
  .github/workflows/driver-adapter-smoke-tests.yml
Labels: topic: driverAdapters

#4229 driver-adapters: libsql/turso adapter
  .envrc
  .github/workflows/driver-adapter-smoke-tests.yml
  .github/workflows/query-engine-driver-adapters.yml
  Makefile
  query-engine/connector-test-kit-rs/query-engine-tests/tests/new/interactive_tx.rs
  query-engine/connector-test-kit-rs/query-engine-tests/tests/new/ref_actions/on_delete/set_default.rs
  query-engine/connector-test-kit-rs/query-engine-tests/tests/new/ref_actions/on_update/set_default.rs
  query-engine/connector-test-kit-rs/query-tests-setup/src/config.rs
  query-engine/connector-test-kit-rs/test-configs/libsql-sqlite
  query-engine/driver-adapters/js/adapter-libsql/.gitignore
  query-engine/driver-adapters/js/adapter-libsql/README.md
  query-engine/driver-adapters/js/adapter-libsql/package.json
  query-engine/driver-adapters/js/adapter-libsql/src/conversion.ts
  query-engine/driver-adapters/js/adapter-libsql/src/index.ts
  query-engine/driver-adapters/js/adapter-libsql/src/libsql.ts
  query-engine/driver-adapters/js/adapter-libsql/tests/types.test.mts
  query-engine/driver-adapters/js/adapter-libsql/tsconfig.build.json
  query-engine/driver-adapters/js/adapter-libsql/tsconfig.json
  query-engine/driver-adapters/js/connector-test-kit-executor/package.json
  query-engine/driver-adapters/js/connector-test-kit-executor/src/index.ts
  query-engine/driver-adapters/js/package.json
  query-engine/driver-adapters/js/pnpm-lock.yaml
  query-engine/driver-adapters/js/pnpm-workspace.yaml
  query-engine/driver-adapters/js/smoke-test-js/.envrc.example
  query-engine/driver-adapters/js/smoke-test-js/.gitignore
  query-engine/driver-adapters/js/smoke-test-js/package.json
  query-engine/driver-adapters/js/smoke-test-js/prisma/sqlite/commands/type_test/insert.sql
  query-engine/driver-adapters/js/smoke-test-js/prisma/sqlite/migrations/20230915202554_init/migration.sql
  query-engine/driver-adapters/js/smoke-test-js/prisma/sqlite/migrations/migration_lock.toml
  query-engine/driver-adapters/js/smoke-test-js/prisma/sqlite/schema.prisma
  query-engine/driver-adapters/js/smoke-test-js/src/client/client.ts
  query-engine/driver-adapters/js/smoke-test-js/src/client/libsql.test.ts
  query-engine/driver-adapters/js/smoke-test-js/src/libquery/libquery.ts
  query-engine/driver-adapters/js/smoke-test-js/src/libquery/libsql.test.ts
  query-engine/driver-adapters/src/conversion.rs
  query-engine/driver-adapters/src/proxy.rs
  query-engine/driver-adapters/src/queryable.rs
Labels: topic: driverAdapters phase 1

#4285 fix(driver-adapters): float rounding problem
  query-engine/driver-adapters/src/conversion.rs
Labels: topic: driverAdapters phase 1

#4286 driver-adapters: close tx on drop
  query-engine/driver-adapters/js/adapter-libsql/package.json
  query-engine/driver-adapters/js/adapter-libsql/src/libsql.ts
  query-engine/driver-adapters/js/adapter-neon/package.json
  query-engine/driver-adapters/js/adapter-neon/src/neon.ts
  query-engine/driver-adapters/js/adapter-pg/package.json
  query-engine/driver-adapters/js/adapter-pg/src/pg.ts
  query-engine/driver-adapters/js/adapter-planetscale/package.json
  query-engine/driver-adapters/js/adapter-planetscale/src/planetscale.ts
  query-engine/driver-adapters/js/driver-adapter-utils/package.json
  query-engine/driver-adapters/js/driver-adapter-utils/src/binder.ts
  query-engine/driver-adapters/js/driver-adapter-utils/src/types.ts
  query-engine/driver-adapters/js/pnpm-lock.yaml
  query-engine/driver-adapters/js/smoke-test-js/package.json
  query-engine/driver-adapters/src/proxy.rs
Labels: topic: driverAdapters phase 1

#4288 driver-adapters: libsql: serialize all operations
  query-engine/driver-adapters/js/adapter-libsql/package.json
  query-engine/driver-adapters/js/adapter-libsql/src/libsql.ts
  query-engine/driver-adapters/js/pnpm-lock.yaml
Labels: topic: driverAdapters phase 1

#4226 driver-adapters: add example of loading the parent .envrc
  query-engine/driver-adapters/js/smoke-test-js/.envrc.example
Labels: topic: driverAdapters phase 1

#4291 Fix JsonNull parsing from neon and pg drivers
  query-engine/connector-test-kit-rs/query-engine-tests/tests/queries/data_types/json.rs
  query-engine/driver-adapters/js/adapter-neon/package.json
  query-engine/driver-adapters/js/adapter-neon/src/conversion.ts
  query-engine/driver-adapters/js/adapter-pg/package.json
  query-engine/driver-adapters/js/adapter-pg/src/conversion.ts
  query-engine/driver-adapters/js/driver-adapter-utils/package.json
  query-engine/driver-adapters/js/driver-adapter-utils/src/const.ts
  query-engine/driver-adapters/js/driver-adapter-utils/src/index.ts
  query-engine/driver-adapters/src/proxy.rs
Labels: topic: driverAdapters phase 1

#4292 fix(driver-adapters) libsql queries containing aggregations
  query-engine/driver-adapters/js/adapter-libsql/package.json
  query-engine/driver-adapters/js/adapter-libsql/src/conversion.ts
  query-engine/driver-adapters/js/driver-adapter-utils/package.json
  query-engine/driver-adapters/js/driver-adapter-utils/src/const.ts
  query-engine/driver-adapters/src/proxy.rs
Labels: topic: driverAdapters phase 1

#4295 driver-adapters: fix Transaction.dispose for pg and neon
  query-engine/driver-adapters/js/adapter-neon/package.json
  query-engine/driver-adapters/js/adapter-neon/src/neon.ts
  query-engine/driver-adapters/js/adapter-pg/package.json
  query-engine/driver-adapters/js/adapter-pg/src/pg.ts
Labels: topic: driverAdapters phase 1

#4280 perf: avoid all internal queries for enums
  quaint/src/ast.rs
  quaint/src/ast/column.rs
  quaint/src/ast/enums.rs
  quaint/src/ast/values.rs
  quaint/src/connector/mssql/conversion.rs
  quaint/src/connector/mysql/conversion.rs
  quaint/src/connector/postgres/conversion.rs
  quaint/src/connector/sqlite/conversion.rs
  quaint/src/serde.rs
  quaint/src/tests/query.rs
  quaint/src/tests/types/mysql.rs
  quaint/src/visitor.rs
  quaint/src/visitor/mssql.rs
  quaint/src/visitor/mysql.rs
  quaint/src/visitor/postgres.rs
  quaint/src/visitor/sqlite.rs
  query-engine/connectors/sql-query-connector/src/model_extensions/column.rs
  query-engine/connectors/sql-query-connector/src/model_extensions/scalar_field.rs
  query-engine/connectors/sql-query-connector/src/query_builder/read.rs
  query-engine/connectors/sql-query-connector/src/query_builder/write.rs
  query-engine/connectors/sql-query-connector/src/row.rs
  query-engine/connectors/sql-query-connector/src/value.rs
  query-engine/connectors/sql-query-connector/src/value_ext.rs
  query-engine/driver-adapters/src/proxy.rs
  query-engine/prisma-models/src/field/mod.rs
  query-engine/prisma-models/src/internal_enum.rs
  schema-engine/sql-migration-tests/src/assertions/quaint_result_set_ext.rs
  schema-engine/sql-migration-tests/tests/migrations/sql.rs
Labels: topic: performance

#4301 driver(adapters): More test fixes focused on neon/pg
  Cargo.lock
  query-engine/driver-adapters/Cargo.toml
  query-engine/driver-adapters/js/adapter-neon/package.json
  query-engine/driver-adapters/js/adapter-neon/src/conversion.ts
  query-engine/driver-adapters/js/adapter-neon/src/neon.ts
  query-engine/driver-adapters/js/adapter-pg/package.json
  query-engine/driver-adapters/js/adapter-pg/src/conversion.ts
  query-engine/driver-adapters/js/adapter-pg/src/pg.ts
  query-engine/driver-adapters/js/driver-adapter-utils/package.json
  query-engine/driver-adapters/js/driver-adapter-utils/src/const.ts
  query-engine/driver-adapters/src/proxy.rs
Labels: topic: driverAdapters phase 1

#4305 fix(qe): Namespace references to enum type names with the schema name.
  quaint/.gitignore
  quaint/Cargo.lock
  quaint/src/ast/enums.rs
  quaint/src/ast/values.rs
  quaint/src/tests/query.rs
  quaint/src/visitor/postgres.rs
  query-engine/connectors/sql-query-connector/src/cursor_condition.rs
  query-engine/connectors/sql-query-connector/src/database/operations/read.rs
  query-engine/connectors/sql-query-connector/src/filter/visitor.rs
  query-engine/connectors/sql-query-connector/src/model_extensions/scalar_field.rs
  query-engine/connectors/sql-query-connector/src/model_extensions/selection_result.rs
  query-engine/connectors/sql-query-connector/src/query_builder/mod.rs
  query-engine/connectors/sql-query-connector/src/query_builder/write.rs
  query-engine/prisma-models/src/internal_enum.rs
Labels: topic: driverAdapters phase 1

#4253 fix: refine error message when retrieving type identifier
  psl/psl-core/src/validate/validation_pipeline/validations.rs
  psl/psl-core/src/validate/validation_pipeline/validations/indexes.rs
  query-engine/prisma-models/src/field/scalar.rs
  query-engine/prisma-models/tests/datamodel_converter_tests.rs
Labels: tech/engines/query engine, quine, bounty/pre-approved
