Repository prisma/prisma-engines, pull requests merged in 2023-10, with the labels that each got.

#4304 psl: un-hide `driverAdapters` preview feature
  psl/psl-core/src/common/preview_features.rs
  psl/psl/tests/config/generators.rs
Labels: topic: driverAdapters phase 1

#4307 driver-adapters: support bytes type in pg and neon
  query-engine/driver-adapters/js/adapter-neon/src/conversion.ts
  query-engine/driver-adapters/js/adapter-pg/src/conversion.ts
  query-engine/driver-adapters/src/conversion.rs
Labels: topic: driverAdapters phase 1

#4308 driver-adapters: support XML columns in pg and neon
  query-engine/driver-adapters/js/adapter-neon/src/conversion.ts
  query-engine/driver-adapters/js/adapter-pg/src/conversion.ts
Labels: topic: driverAdapters phase 1

#4312 driver-adapters: bump package versions for publishing
  query-engine/driver-adapters/js/adapter-libsql/package.json
  query-engine/driver-adapters/js/adapter-neon/package.json
  query-engine/driver-adapters/js/adapter-pg/package.json
  query-engine/driver-adapters/js/adapter-planetscale/package.json
  query-engine/driver-adapters/js/driver-adapter-utils/package.json
Labels: topic: driverAdapters phase 1

#4302 ci: Driver Adapters versioning post 5.4.0
  .github/workflows/publish-driver-adapters.yml
  query-engine/driver-adapters/js/adapter-libsql/package.json
  query-engine/driver-adapters/js/adapter-neon/package.json
  query-engine/driver-adapters/js/adapter-pg/package.json
  query-engine/driver-adapters/js/adapter-planetscale/package.json
  query-engine/driver-adapters/js/driver-adapter-utils/package.json
Labels: topic: driverAdapters phase 1

#4320 adapter-planetscale: handle NULL column type
  query-engine/connector-test-kit-rs/query-engine-tests/src/utils/raw.rs
  query-engine/connector-test-kit-rs/query-engine-tests/tests/new/regressions/mod.rs
  query-engine/connector-test-kit-rs/query-engine-tests/tests/new/regressions/prisma_21369.rs
  query-engine/driver-adapters/js/adapter-planetscale/src/conversion.ts
Labels: topic: driverAdapters phase 1

#4337 fix(smoke-test): add assertion for expected error
  query-engine/driver-adapters/js/smoke-test-js/README.md
  query-engine/driver-adapters/js/smoke-test-js/package.json
  query-engine/driver-adapters/js/smoke-test-js/prisma/sqlite/migrations/20230915202554_init/migration.sql
  query-engine/driver-adapters/js/smoke-test-js/prisma/sqlite/schema.prisma
  query-engine/driver-adapters/js/smoke-test-js/src/libquery/libquery.ts
Labels: topic: driverAdapters phase 1

#4333 feat(query-engine): add skeleton for Wasm Query Engine
  Cargo.lock
  Cargo.toml
  query-engine/query-engine-wasm/.gitignore
  query-engine/query-engine-wasm/.nvmrc
  query-engine/query-engine-wasm/Cargo.toml
  query-engine/query-engine-wasm/README.md
  query-engine/query-engine-wasm/build.rs
  query-engine/query-engine-wasm/build.sh
  query-engine/query-engine-wasm/example.js
  query-engine/query-engine-wasm/package-lock.json
  query-engine/query-engine-wasm/package.json
  query-engine/query-engine-wasm/src/engine.rs
  query-engine/query-engine-wasm/src/error.rs
  query-engine/query-engine-wasm/src/functions.rs
  query-engine/query-engine-wasm/src/lib.rs
  query-engine/query-engine-wasm/src/logger.rs
  query-engine/query-engine-wasm/src/proxy.rs
Labels: topic: driverAdapters phase 2

#4351 Driver adapters phase 1 correctness: implement flavor-specific driver adapter conversions for postgres dates
  quaint/src/ast/values.rs
  query-engine/connectors/sql-query-connector/src/model_extensions/scalar_field.rs
  query-engine/driver-adapters/js/adapter-neon/package.json
  query-engine/driver-adapters/js/adapter-neon/src/conversion.ts
  query-engine/driver-adapters/js/adapter-pg/package.json
  query-engine/driver-adapters/js/adapter-pg/src/conversion.ts
  query-engine/driver-adapters/js/pnpm-lock.yaml
  query-engine/driver-adapters/src/conversion.rs
  query-engine/driver-adapters/src/conversion/postgres.rs
  query-engine/driver-adapters/src/proxy.rs
  query-engine/driver-adapters/src/queryable.rs
Labels: topic: driverAdapters phase 1

#4357 Fix binary entrypoint for planetscale tests
  docker-compose.yml
  docker/planetscale_proxy/Dockerfile
Labels: topic: driverAdapters phase 1

#4371 ci(biuildkite): skip test&build for changes in query-engine/query-engine-wasm
  .buildkite/engineer
Labels: topic: driverAdapters phase 1

#4231 feat(core): add fork of `cuid` with wasm32-unknown-unknown support
  Cargo.lock
  query-engine/connectors/mongodb-query-connector/Cargo.toml
  query-engine/connectors/sql-query-connector/Cargo.toml
  query-engine/core/Cargo.toml
  query-engine/dmmf/Cargo.toml
  query-engine/prisma-models/Cargo.toml
Labels: topic: driverAdapters phase 2

#4398 Fix driver adapters tests after migration of driver adapters to prisma
  .gitignore
  Makefile
  query-engine/driver-adapters/connector-test-kit-executor/package.json
  query-engine/driver-adapters/connector-test-kit-executor/pnpm-lock.yaml
  query-engine/driver-adapters/js/.nvmrc
  query-engine/driver-adapters/package.json
  query-engine/driver-adapters/pnpm-workspace.yaml
Labels: topic: tech debt
