Repository prisma/prisma-engines, pull requests merged in 2024-06, with the labels that each got.

#4899 fix(fmt): newlines for composite types (and enums)
  prisma-fmt/src/code_actions/block.rs
  prisma-fmt/tests/code_actions/scenarios/create_missing_block_composite_type_crlf/.gitattributes
  prisma-fmt/tests/code_actions/scenarios/create_missing_block_composite_type_crlf/result.json
  prisma-fmt/tests/code_actions/scenarios/create_missing_block_composite_type_crlf/schema.prisma
  prisma-fmt/tests/code_actions/tests.rs
  psl/parser-database/src/walkers.rs
  psl/parser-database/src/walkers/composite_type.rs
  psl/parser-database/src/walkers/enum.rs
  psl/parser-database/src/walkers/model.rs
Labels: PR: Bug

#4917 tech(quaint): surface mysql socket as host if in use
  quaint/src/connector/mysql/url.rs
Labels: PR: Improvement

#4919 tech(fmt): use wasm logging
  prisma-schema-wasm/scripts/update-schema-wasm.sh
  prisma-schema-wasm/src/lib.rs
Labels: domain/schema, PR: Improvement

#4815 fix(prisma-fmt): use UTF-16 offset in the response for the schema that contains multi-byte characters
  prisma-fmt/src/code_actions.rs
  prisma-fmt/src/code_actions/block.rs
  prisma-fmt/src/code_actions/relations.rs
  prisma-fmt/src/lib.rs
  prisma-fmt/src/lint.rs
  prisma-fmt/src/main.rs
  prisma-fmt/src/offsets.rs
  prisma-fmt/src/text_document_completion.rs
  prisma-fmt/tests/code_actions/test_api.rs
  psl/diagnostics/src/pretty_print.rs
Labels: PR: Bug

#4924 tech(fmt): extract LSPContext struct
  prisma-fmt/src/code_actions.rs
  prisma-fmt/src/code_actions/block.rs
  prisma-fmt/src/code_actions/relations.rs
  prisma-fmt/src/lib.rs
  prisma-fmt/src/text_document_completion.rs
Labels: PR: Improvement

#4933 tech(fmt/psl): prep-work for further language-server support
  prisma-fmt/src/code_actions/relation_mode.rs
  psl/parser-database/src/lib.rs
  psl/parser-database/src/names.rs
  psl/parser-database/src/names/reserved_model_names.rs
  psl/parser-database/src/walkers.rs
  psl/parser-database/src/walkers/enum.rs
  psl/parser-database/src/walkers/model.rs
  psl/parser-database/src/walkers/top.rs
  psl/psl-core/src/validate/datasource_loader.rs
  psl/psl-core/src/validate/generator_loader.rs
  psl/schema-ast/src/ast.rs
  psl/schema-ast/src/ast/config.rs
  psl/schema-ast/src/ast/enum.rs
  psl/schema-ast/src/ast/field.rs
  psl/schema-ast/src/ast/find_at_position.rs
  psl/schema-ast/src/ast/find_at_position/attribute.rs
  psl/schema-ast/src/ast/find_at_position/composite_type.rs
  psl/schema-ast/src/ast/find_at_position/datasource.rs
  psl/schema-ast/src/ast/find_at_position/enum.rs
  psl/schema-ast/src/ast/find_at_position/expression.rs
  psl/schema-ast/src/ast/find_at_position/field.rs
  psl/schema-ast/src/ast/find_at_position/generator.rs
  psl/schema-ast/src/ast/find_at_position/model.rs
  psl/schema-ast/src/ast/find_at_position/property.rs
  psl/schema-ast/src/ast/source_config.rs
  psl/schema-ast/src/ast/top.rs
Labels: PR: Improvement
